---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: device-plugin-example
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - update
      - patch
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: device-plugin-example
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: device-plugin-example
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: device-plugin-example
subjects:
  - kind: ServiceAccount
    name: device-plugin-example
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-example
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: device-plugin-example
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: device-plugin-example
    spec:
      serviceAccount: device-plugin-example
      containers:
        - image: lleiiell/k8s-device-plugin-example:v0.1
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          args:
            - k8s-device-plugin-example
            - -logtostderr
            - --v=5
          name: device-plugin-example
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "300Mi"
              cpu: "200m"
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/kubelet.config
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins