
apiVersion: v1
kind: Pod
metadata:
  name: test-plugin-pod
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c","trap : TERM INT; sleep infinity & wait"]
      name: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          example.com/device: "1"
          cpu: "500m"
          memory: "500Mi"